name: flutter_work_spaces
description: A new Flutter project

environment:
  sdk: "^3.7.0"
dependencies:
  http: ^1.3.0
# dependencies:
#   flutter:
#     sdk: flutter

#   cupertino_icons: ^1.0.2

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.0

# flutter:
#   uses-material-design: true
